# Generated by Django 3.2.14 on 2022-08-17 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_herocontent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='herocontent',
            old_name='content',
            new_name='hero_content',
        ),
        migrations.RenameField(
            model_name='herocontent',
            old_name='excerpt',
            new_name='hero_excerpt',
        ),
        migrations.RenameField(
            model_name='herocontent',
            old_name='featured_image',
            new_name='hero_featured_image',
        ),
        migrations.RenameField(
            model_name='herocontent',
            old_name='title',
            new_name='hero_title',
        ),
    ]
