# Generated by Django 3.2.14 on 2022-08-20 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20220817_0918'),
    ]

    operations = [
        migrations.RenameField(
            model_name='herocontent',
            old_name='slug',
            new_name='hero_slug',
        ),
        migrations.AlterField(
            model_name='herocontent',
            name='hero_content',
            field=models.TextField(blank=True),
        ),
    ]
