# Generated by Django 3.2.14 on 2022-08-21 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20220820_0351'),
    ]

    operations = [
        migrations.AddField(
            model_name='herocontent',
            name='hero_image_alt',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
