# Generated by Django 3.2.14 on 2022-08-22 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_herocontent_hero_image_alt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='herocontent',
            old_name='hero_image_alt',
            new_name='image_alt_text',
        ),
        migrations.AddField(
            model_name='herocontent',
            name='hero_header',
            field=models.TextField(blank=True),
        ),
    ]
