# Generated by Django 3.2.14 on 2022-08-22 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20220822_0319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='herocontent',
            name='hero_header',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='herocontent',
            name='image_alt_text',
            field=models.CharField(blank=True, default='aden wellness theme image', max_length=200),
        ),
    ]
