# Generated by Django 3.2.14 on 2022-08-22 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20220822_0335'),
    ]

    operations = [
        migrations.AddField(
            model_name='herocontent',
            name='image_place',
            field=models.IntegerField(choices=[(1, 'Image-on-top'), (2, 'Image-on-side'), (3, 'Image-as-background')], default=3),
        ),
        migrations.AlterField(
            model_name='herocontent',
            name='images_on_page',
            field=models.IntegerField(choices=[(12, 'Whole Page'), (6, '2xPage')], default=12),
        ),
    ]
