# Generated by Django 3.2.14 on 2022-08-22 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20220822_1653'),
    ]

    operations = [
        migrations.RenameField(
            model_name='herocontent',
            old_name='images_on_page',
            new_name='images_on_mobile_page',
        ),
        migrations.AddField(
            model_name='herocontent',
            name='images_on_desktop',
            field=models.IntegerField(choices=[(12, 'Whole Page'), (6, '2xPage'), (4, '3xPage'), (3, '4xPage')], default=6),
        ),
    ]
