# Generated by Django 3.2.14 on 2022-08-24 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_rename_contactus_contactmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='herocontent',
            name='image_height',
            field=models.IntegerField(choices=[(32, '320px'), (27, '270px'), (16, '160px'), (8, '88px')], default=27),
        ),
    ]
