# Generated by Django 3.2.14 on 2022-08-28 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_rename_hero_slug_herocontent_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='herocontent',
            old_name='slug',
            new_name='hero_slug',
        ),
    ]
