# Generated by Django 3.2.14 on 2022-09-09 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_alter_herocontent_images_on_desktop'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='herocontent',
            name='hero_card',
        ),
    ]
