# Generated by Django 3.2.14 on 2022-09-09 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_remove_herocontent_hero_card'),
    ]

    operations = [
        migrations.RenameField(
            model_name='herocontent',
            old_name='hero_slug',
            new_name='slug',
        ),
    ]
