# Generated by Django 3.2.14 on 2022-09-11 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0023_post_posted_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='herocontent',
            name='text_backround',
            field=models.IntegerField(choices=[(1, 'No background'), (2, 'Put background')], default=1),
        ),
    ]
