# Generated by Django 3.2.14 on 2022-09-11 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0024_herocontent_text_backround'),
    ]

    operations = [
        migrations.RenameField(
            model_name='herocontent',
            old_name='text_backround',
            new_name='text_background',
        ),
    ]
