# Generated by Django 3.2.14 on 2022-09-13 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0027_alter_post_created_on'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='post',
            name='order',
            field=models.IntegerField(default=1),
        ),
    ]
